language: node_js
node_js: stable

install:
  - npm install


script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Aubergines"
  - git config user.email "chinazhaoshuangquan@gmail.com"
  - git add .
  - git commit -m "Update - auto deploy by Travis CI."
  - git push --force --quiet "https://${gitHubToken}@${GITHUB_REF}" master:master

branches:
  only:
    - blog_source
env:
  global:
    - GITHUB_REF: github.com/Aubergines/Aubergines.github.io.git
