branches: 
  only: 
    - blog-source
env: 
  global: 
    - 
      GH_REF: github.com/Aubergines/Aubergines.github.io.git
install: 
  - "npm install"
language: node_js
node_js: stable
script: 
  - "hexo cl"
  - "hexo g"
  - "cd ./public"
  - "git init"
  - "git config user.name \"Aubergines\""
  - "git config user.email \"chinazhaoshuangquan@gmail.com\""
  - "git add ."
  - "git commit -m \"update\""
  - "git push --force --quiet \"https://${gitHubToken}@${GH_REF}\" master:master"